# -------------------------------------------------------------------
# Services
# -------------------------------------------------------------------
services:
  app:
    container_name: hackathon_app
    build:
      context: .
    volumes:
      - ./data:/data
    networks:
      - backend
    env_file:
      - .env
    restart: unless-stopped
    ports: [ "8000:8000" ]


# -------------------------------------------------------------------
# Volumes & network
# -------------------------------------------------------------------
networks:
  backend:
